// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Accommodation documents
 */
interface AccommodationDocumentData {
  /**
   * Name field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Taj Palace Hotel
   * - **API ID Path**: accommodation.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * City field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: New Delhi
   * - **API ID Path**: accommodation.city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  city: prismic.KeyTextField;

  /**
   * State field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Delhi
   * - **API ID Path**: accommodation.state
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  state: prismic.KeyTextField;

  /**
   * Location field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Near Apollo Hospital, Sarita Vihar
   * - **API ID Path**: accommodation.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Distance field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 2 km
   * - **API ID Path**: accommodation.distance
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  distance: prismic.KeyTextField;

  /**
   * Price per night field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: $100 - $150 / night
   * - **API ID Path**: accommodation.price_range
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price_range: prismic.KeyTextField;

  /**
   * Nearby Hospital field in *Accommodation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation.nearby_hospital
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  nearby_hospital: prismic.ContentRelationshipField<"hospital">;

  /**
   * Image field in *Accommodation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Recovery Amenities/Features field in *Accommodation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation.features
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  features: prismic.RichTextField;

  /**
   * About Current Accommodation field in *Accommodation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Guest Rating field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., 4.8 Guest Rating
   * - **API ID Path**: accommodation.rating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  rating: prismic.KeyTextField; /**
   * Meta Title field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: accommodation.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Accommodation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: accommodation.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Accommodation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodation.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Accommodation document from Prismic
 *
 * - **API ID**: `accommodation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccommodationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AccommodationDocumentData>,
    "accommodation",
    Lang
  >;

/**
 * Content for Doctor documents
 */
interface DoctorDocumentData {
  /**
   * Name field in *Doctor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Dr. Arun Prasad
   * - **API ID Path**: doctor.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Specialty field in *Doctor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cardiothoracic Surgeon
   * - **API ID Path**: doctor.specialty
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  specialty: prismic.KeyTextField;

  /**
   * Experience field in *Doctor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 25+ Years
   * - **API ID Path**: doctor.experience
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  experience: prismic.KeyTextField;

  /**
   * Affiliated Hospital field in *Doctor*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: doctor.hospital
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  hospital: prismic.ContentRelationshipField<"hospital">;

  /**
   * Profile Image field in *Doctor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: doctor.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Biography field in *Doctor*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: doctor.biography
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  biography: prismic.RichTextField;

  /**
   * Rating field in *Doctor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., 4.9/5 Rating
   * - **API ID Path**: doctor.rating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  rating: prismic.KeyTextField;

  /**
   * Accepting New Patients field in *Doctor*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: doctor.accepting_patients
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  accepting_patients: prismic.BooleanField;

  /**
   * Free Initial Video Consultation field in *Doctor*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: doctor.free_consultation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  free_consultation: prismic.BooleanField; /**
   * Meta Title field in *Doctor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: doctor.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Doctor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: doctor.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Doctor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: doctor.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Doctor document from Prismic
 *
 * - **API ID**: `doctor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DoctorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DoctorDocumentData>, "doctor", Lang>;

/**
 * Content for Hospital documents
 */
interface HospitalDocumentData {
  /**
   * Name field in *Hospital*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Apollo Hospital, Delhi
   * - **API ID Path**: hospital.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Location field in *Hospital*
   *
   * - **Field Type**: Text
   * - **Placeholder**: New Delhi
   * - **API ID Path**: hospital.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Specialties field in *Hospital*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cardiology, Orthopedics, Oncology
   * - **API ID Path**: hospital.specialties
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  specialties: prismic.KeyTextField;

  /**
   * Accreditations field in *Hospital*
   *
   * - **Field Type**: Text
   * - **Placeholder**: JCI, NABH
   * - **API ID Path**: hospital.accreditations
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  accreditations: prismic.KeyTextField;

  /**
   * Image field in *Hospital*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hospital.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * About This Hospital field in *Hospital*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hospital.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Free Airport Transfers Included field in *Hospital*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hospital.free_airport_transfers
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  free_airport_transfers: prismic.BooleanField;

  /**
   * Dedicated International Translators field in *Hospital*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hospital.international_translators
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  international_translators: prismic.BooleanField;

  /**
   * Key Specialties Description field in *Hospital*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g., Renowned departments equipped with state-of-the-art...
   * - **API ID Path**: hospital.key_specialties_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  key_specialties_text: prismic.RichTextField; /**
   * Meta Title field in *Hospital*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hospital.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Hospital*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hospital.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Hospital*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hospital.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Hospital document from Prismic
 *
 * - **API ID**: `hospital`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HospitalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HospitalDocumentData>,
    "hospital",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | FeaturesSlice
  | TestimonialsSlice
  | ProcessSlice
  | CtaSlice
  | ProceduresGridSlice
  | HospitalsGridSlice
  | DoctorsGridSlice
  | AccommodationsGridSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slices field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Procedure documents
 */
interface ProcedureDocumentData {
  /**
   * Name field in *Procedure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Heart Bypass Surgery
   * - **API ID Path**: procedure.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Procedure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief overview of the procedure...
   * - **API ID Path**: procedure.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Cost Range field in *Procedure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: $4,500 - $6,500
   * - **API ID Path**: procedure.cost_range
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cost_range: prismic.KeyTextField;

  /**
   * Image field in *Procedure*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Rich Description field in *Procedure*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detailed information about the procedure, recovery, etc.
   * - **API ID Path**: procedure.rich_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_description: prismic.RichTextField;

  /**
   * Success Rate Text field in *Procedure*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g., Our network boasts a 99% success rate...
   * - **API ID Path**: procedure.success_rate_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  success_rate_text: prismic.RichTextField;

  /**
   * Recovery Time Duration field in *Procedure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., 7 - 14 Days
   * - **API ID Path**: procedure.recovery_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  recovery_time: prismic.KeyTextField;

  /**
   * Recovery Description field in *Procedure*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g., Most patients can travel back home safely within 2 to 3 weeks...
   * - **API ID Path**: procedure.recovery_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  recovery_text: prismic.RichTextField; /**
   * Meta Title field in *Procedure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: procedure.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Procedure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: procedure.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Procedure*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Procedure document from Prismic
 *
 * - **API ID**: `procedure`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProcedureDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProcedureDocumentData>,
    "procedure",
    Lang
  >;

export type AllDocumentTypes =
  | AccommodationDocument
  | DoctorDocument
  | HospitalDocument
  | PageDocument
  | ProcedureDocument;

/**
 * Primary content in *AccommodationsGrid → Default → Primary*
 */
export interface AccommodationsGridSliceDefaultPrimary {
  /**
   * Title field in *AccommodationsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodations_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *AccommodationsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodations_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AccommodationsGrid → Items*
 */
export interface AccommodationsGridSliceDefaultItem {
  /**
   * Accommodation field in *AccommodationsGrid → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: accommodations_grid.items[].item
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  item: prismic.ContentRelationshipField<"accommodation">;
}

/**
 * Default variation for AccommodationsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccommodationsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccommodationsGridSliceDefaultPrimary>,
  Simplify<AccommodationsGridSliceDefaultItem>
>;

/**
 * Slice variation for *AccommodationsGrid*
 */
type AccommodationsGridSliceVariation = AccommodationsGridSliceDefault;

/**
 * AccommodationsGrid Shared Slice
 *
 * - **API ID**: `accommodations_grid`
 * - **Description**: Grid of selected accommodations
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccommodationsGridSlice = prismic.SharedSlice<
  "accommodations_grid",
  AccommodationsGridSliceVariation
>;

/**
 * Primary content in *CTA → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Title field in *CTA → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CTA → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *CTA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *CTA → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Text field in *CTA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_text: prismic.KeyTextField;
}

/**
 * Default variation for CTA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CTA*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * CTA Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Call-to-action section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *DoctorsGrid → Default → Primary*
 */
export interface DoctorsGridSliceDefaultPrimary {
  /**
   * Title field in *DoctorsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: doctors_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *DoctorsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: doctors_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *DoctorsGrid → Items*
 */
export interface DoctorsGridSliceDefaultItem {
  /**
   * Doctor field in *DoctorsGrid → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: doctors_grid.items[].item
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  item: prismic.ContentRelationshipField<"doctor">;
}

/**
 * Default variation for DoctorsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DoctorsGridSliceDefaultPrimary>,
  Simplify<DoctorsGridSliceDefaultItem>
>;

/**
 * Slice variation for *DoctorsGrid*
 */
type DoctorsGridSliceVariation = DoctorsGridSliceDefault;

/**
 * DoctorsGrid Shared Slice
 *
 * - **API ID**: `doctors_grid`
 * - **Description**: Grid of selected doctors
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorsGridSlice = prismic.SharedSlice<
  "doctors_grid",
  DoctorsGridSliceVariation
>;

/**
 * Primary content in *Features → Default → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Title field in *Features → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Features → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSliceDefaultItem {
  /**
   * Emoji Icon field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 🏥
   * - **API ID Path**: features.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Item Title field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Item Description field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  Simplify<FeaturesSliceDefaultItem>
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features section with a list of items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Hero Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with title, subtitle and image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HospitalsGrid → Default → Primary*
 */
export interface HospitalsGridSliceDefaultPrimary {
  /**
   * Title field in *HospitalsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hospitals_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *HospitalsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hospitals_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *HospitalsGrid → Items*
 */
export interface HospitalsGridSliceDefaultItem {
  /**
   * Hospital field in *HospitalsGrid → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hospitals_grid.items[].item
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  item: prismic.ContentRelationshipField<"hospital">;
}

/**
 * Default variation for HospitalsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HospitalsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HospitalsGridSliceDefaultPrimary>,
  Simplify<HospitalsGridSliceDefaultItem>
>;

/**
 * Slice variation for *HospitalsGrid*
 */
type HospitalsGridSliceVariation = HospitalsGridSliceDefault;

/**
 * HospitalsGrid Shared Slice
 *
 * - **API ID**: `hospitals_grid`
 * - **Description**: Grid of selected hospitals
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HospitalsGridSlice = prismic.SharedSlice<
  "hospitals_grid",
  HospitalsGridSliceVariation
>;

/**
 * Primary content in *ProceduresGrid → Default → Primary*
 */
export interface ProceduresGridSliceDefaultPrimary {
  /**
   * Title field in *ProceduresGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: procedures_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProceduresGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: procedures_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ProceduresGrid → Items*
 */
export interface ProceduresGridSliceDefaultItem {
  /**
   * Procedure field in *ProceduresGrid → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: procedures_grid.items[].item
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  item: prismic.ContentRelationshipField<"procedure">;
}

/**
 * Default variation for ProceduresGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProceduresGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProceduresGridSliceDefaultPrimary>,
  Simplify<ProceduresGridSliceDefaultItem>
>;

/**
 * Slice variation for *ProceduresGrid*
 */
type ProceduresGridSliceVariation = ProceduresGridSliceDefault;

/**
 * ProceduresGrid Shared Slice
 *
 * - **API ID**: `procedures_grid`
 * - **Description**: Grid of selected procedures
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProceduresGridSlice = prismic.SharedSlice<
  "procedures_grid",
  ProceduresGridSliceVariation
>;

/**
 * Primary content in *Process → Default → Primary*
 */
export interface ProcessSliceDefaultPrimary {
  /**
   * Title field in *Process → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Process → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Process → Items*
 */
export interface ProcessSliceDefaultItem {
  /**
   * Step Number field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 01
   * - **API ID Path**: process.items[].step_number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_number: prismic.KeyTextField;

  /**
   * Step Title field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Step Description field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Process Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessSliceDefaultPrimary>,
  Simplify<ProcessSliceDefaultItem>
>;

/**
 * Slice variation for *Process*
 */
type ProcessSliceVariation = ProcessSliceDefault;

/**
 * Process Shared Slice
 *
 * - **API ID**: `process`
 * - **Description**: Step-by-step process section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSlice = prismic.SharedSlice<
  "process",
  ProcessSliceVariation
>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Patient Name field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Country field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].country
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  country: prismic.KeyTextField;

  /**
   * Procedure field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].procedure
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  procedure: prismic.KeyTextField;

  /**
   * Testimonial Text field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Rating (1-5) field in *Testimonials → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Patient testimonials section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AccommodationDocument,
      AccommodationDocumentData,
      DoctorDocument,
      DoctorDocumentData,
      HospitalDocument,
      HospitalDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProcedureDocument,
      ProcedureDocumentData,
      AllDocumentTypes,
      AccommodationsGridSlice,
      AccommodationsGridSliceDefaultPrimary,
      AccommodationsGridSliceDefaultItem,
      AccommodationsGridSliceVariation,
      AccommodationsGridSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      DoctorsGridSlice,
      DoctorsGridSliceDefaultPrimary,
      DoctorsGridSliceDefaultItem,
      DoctorsGridSliceVariation,
      DoctorsGridSliceDefault,
      FeaturesSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceDefaultItem,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HospitalsGridSlice,
      HospitalsGridSliceDefaultPrimary,
      HospitalsGridSliceDefaultItem,
      HospitalsGridSliceVariation,
      HospitalsGridSliceDefault,
      ProceduresGridSlice,
      ProceduresGridSliceDefaultPrimary,
      ProceduresGridSliceDefaultItem,
      ProceduresGridSliceVariation,
      ProceduresGridSliceDefault,
      ProcessSlice,
      ProcessSliceDefaultPrimary,
      ProcessSliceDefaultItem,
      ProcessSliceVariation,
      ProcessSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
