// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  features: dynamic(() => import("./Features")),
  testimonials: dynamic(() => import("./Testimonials")),
  process: dynamic(() => import("./Process")),
  cta: dynamic(() => import("./CTA")),
  procedures_grid: dynamic(() => import("./ProceduresGrid")),
  hospitals_grid: dynamic(() => import("./HospitalsGrid")),
  doctors_grid: dynamic(() => import("./DoctorsGrid")),
  accommodations_grid: dynamic(() => import("./AccommodationsGrid")),
  stats: dynamic(() => import("./Stats")),
  team: dynamic(() => import("./Team")),
  about_section: dynamic(() => import("./AboutSection")),
};
